### ISSUE TITLE
REQUEST: Same activator gesture to enable/disable dim

### ISSUE THREAD

**Issue by joemerlino** [thomasfinch/Dim#5]
As the title, it would be great to have just one activator gesture to enable and disable the tweak, for example i used the triple press to activate it but i can't use the same gesture to disable it. Thanks in advance!

**Comment by thomasfinch** [comment]
This is a great idea, I'll add it soon. Thanks for the suggestion!

**Comment by thomasfinch** [comment]
Added in version 1.3
